export const SET_LAST_POSITION = "SET_LAST_POSITION";
export const SET_UNIT = "SET_UNIT";
export const SET_IN_MOTION = "SET_IN_MOTION";
export const SET_CURRENT_SPEED = "SET_CURRENT_SPEED";
export const SET_DISTANCE = "SET_DISTANCE";
export const SET_AVERAGE_SPEED = "SET_AVERAGE_SPEED";
export const SET_TIME_IN_MOTION = "SET_TIME_IN_MOTION";
